In [5]:
import pandas as pd
import numpy as np

omics_data = pd.read_csv("../../Data/Data_Braun/RnaExpression.csv")
print(omics_data.shape)
omics_data.head()

(40934, 312)

,gene_id,EA595454,EA595455,EA595473,EA595500,EA595522,EA595529,EA595564,EA595565,EA595585,...,RCC_18_T_SCR,RCC_21_T_SCR,RCC_27_T_SCR,RCC_41_T_SCR,RCC_50_T_SCR,RCC_73_T_SCR,RCC_90_T_SCR,RCC_93_T_SCR,RCC_96_T_SCR,RCC_99_T_SCR
0,ENSG00000223972.5,26.54007,26.12424,21.95920,28.63682,23.43039,25.17852,25.99338,26.26084,18.44368,...,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566
1,ENSG00000227232.5,33.80347,34.59298,34.42450,34.64308,33.72739,33.92622,33.30467,33.87218,33.61009,...,33.33957,34.17589,33.28113,32.76760,34.65695,34.49380,34.18235,32.95368,35.16618,34.25668
2,ENSG00000284332.1,28.53545,20.59122,27.72119,20.59122,20.59122,20.59122,20.59122,20.59122,20.59122,...,22.66178,22.66178,22.66178,22.66178,33.44038,22.66178,22.66178,22.66178,22.66178,22.66178
3,ENSG00000237613.2,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,...,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501
4,ENSG00000268020.3,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,...,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332

In [36]:
expression_matrix = omics_data.set_index('gene_id')
sum_expression = expression_matrix.sum(axis = 1)
zero_genes = sum_expression[sum_expression == 0].keys().tolist()

variances_expression = eHxpression_matrix.var(axis = 1)
near_zero_var = variances_expression[variances_expression <= 0.0005].keys().tolist()

remove_genes = set(zero_genes) | set(near_zero_var)

In [37]:
remove_genes

set()

In [30]:
expression_matrix_t = expression_matrix.T

In [ ]:
variances_expression

In [15]:
variances_expression[list(remove_genes)[0]]

np.float64(0.006928940120205366)

In [24]:
expression_matrix.loc['ENSG00000260254.1'].var()

np.float64(0.0005535501494866286)

In [2]:
expression_matrix = su2c_rna_ensemble.set_index('Description')
sum_expression = expression_matrix.sum(axis = 1)
zero_genes = sum_expression[sum_expression == 0].keys().tolist()

variances_expression = expression_matrix.var(axis = 1)
near_zero_var = variances_expression[variances_expression <= 0.01].keys().tolist()

remove_genes = set(zero_genes) | set(near_zero_var)

cleaned_expression_matrix = expression_matrix.drop(index = remove_genes)
# cleaned_expression_matrix.to_csv('cleaned_rna_expression.csv', index = True)

,gene_id,EA595454,EA595455,EA595473,EA595500,EA595522,EA595529,EA595564,EA595565,EA595585,...,RCC_18_T_SCR,RCC_21_T_SCR,RCC_27_T_SCR,RCC_41_T_SCR,RCC_50_T_SCR,RCC_73_T_SCR,RCC_90_T_SCR,RCC_93_T_SCR,RCC_96_T_SCR,RCC_99_T_SCR
0,ENSG00000223972.5,26.54007,26.12424,21.95920,28.63682,23.43039,25.17852,25.99338,26.26084,18.44368,...,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566,24.32566
1,ENSG00000227232.5,33.80347,34.59298,34.42450,34.64308,33.72739,33.92622,33.30467,33.87218,33.61009,...,33.33957,34.17589,33.28113,32.76760,34.65695,34.49380,34.18235,32.95368,35.16618,34.25668
2,ENSG00000284332.1,28.53545,20.59122,27.72119,20.59122,20.59122,20.59122,20.59122,20.59122,20.59122,...,22.66178,22.66178,22.66178,22.66178,33.44038,22.66178,22.66178,22.66178,22.66178,22.66178
3,ENSG00000237613.2,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,20.97285,...,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501,21.16501
4,ENSG00000268020.3,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,20.96062,...,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332,21.05332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40929,ENSG00000210176.1,21.10332,21.10332,21.10332,21.10332,21.10332,21.10332,21.10332,21.10332,21.10332,...,21.12900,21.12900,21.12900,21.12900,21.12900,21.12900,21.12900,21.12900,21.12900,21.12900
40930,ENSG00000198786.2,33.06912,34.10239,32.30418,35.00759,32.84753,32.92228,33.29065,33.86834,33.87418,...,34.52259,32.72106,32.31397,33.38951,32.19913,32.65807,28.72786,33.77552,31.52889,33.72443
40931,ENSG00000198695.2,33.38153,34.41628,32.09198,35.55580,32.33502,32.66630,33.48115,33.91942,33.76213,...,33.98006,31.84641,31.13862,32.49081,32.63731,33.26675,28.06082,33.56121,30.79615,32.95976
40932,ENSG00000210194.1,21.21964,21.21964,21.21964,21.21964,21.21964,21.21964,21.21964,21.21964,21.21964,...,21.26248,21.26248,21.26248,21.26248,21.26248,21.26248,21.26248,21.26248,21.26248,21.26248
40933,ENSG00000198727.2,32.54588,33.72339,31.66722,34.64529,32.88763,32.63732,32.49750,34.23793,34.21982,...,34.63528,31.02518,30.87252,32.47631,32.12105,33.34086,28.19728,33.39046,30.15240,32.94716