In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# source_data_path = "/mnt/digphat/syntheticDataBenchmark/Chuong_pipeline/ExperimentNSCLC/LungCancer_ICB/Source Data/"
source_data_path = '/bettik/PROJECTS/pr-ai4drug/trinhtc/workspace/digphat/syntheticDataBenchmark/Chuong_pipeline/ExperimentNSCLC/LungCancer_ICB/Source Data/'
source_data_path_clinical = source_data_path + 'Clinical/'
source_data_path_exome = source_data_path + 'Exome/'
source_data_path_rna = source_data_path + 'RNA/'
source_data_path_ref = source_data_path + 'Reference/'
source_data_path_int = source_data_path + 'Integrative/'
source_data_path_out = source_data_path + 'Output/'

## **Clean Transcriptomics Data**

In [9]:
su2c_rna_harm = pd.read_csv(source_data_path_rna + 'SU2C-MARK_Harmonized_rnaseqc_tpm_v1.gct',skiprows=2,sep='\t')
su2c_rna_harm.head()

,Name,Description,SU2CLC-CLE-NIVO10-T1,SU2CLC-CLE-NIVO18-T1,SU2CLC-CLE-NIVO19-T1,SU2CLC-CLE-NIVO2-T1,SU2CLC-CLE-NIVO20-T1,SU2CLC-CLE-NIVO21-T1,SU2CLC-CLE-NIVO24-T1,SU2CLC-CLE-NIVO3-T1,...,SU2CLC-MSK-A2013-T1,SU2CLC-MSK-A2014-T1,SU2CLC-MSK-A2060-T1,SU2CLC-MSK-A2075-T1,SU2CLC-UCD-1124-T1,SU2CLC-UCD-1137-T1,SU2CLC-UCD-1142-T1,SU2CLC-UCD-1143-T1,SU2CLC-UCD-1557-T1,SU2CLC-UCD-1560-T1
0,ENSG00000223972.5,DDX11L1,0.00000,0.0000,0.465325,0.663131,0.038447,0.0000,0.036191,0.083753,...,0.057543,0.009227,0.00000,0.056734,0.018465,0.507545,0.02658,0.236091,0.0000,0.15309
1,ENSG00000227232.5,WASH7P,1.72811,13.2271,17.226100,9.344120,10.023100,44.2401,0.511251,9.400640,...,9.951610,1.315370,1.37496,7.067370,6.450200,5.491240,4.19865,3.714150,55.4283,4.32528
2,ENSG00000278267.1,MIR6859-1,0.00000,0.0000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.00000
3,ENSG00000243485.5,MIR1302-2HG,0.00000,0.0000,0.000000,0.000000,0.000000,0.0000,0.215248,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.188272,0.047259,0.00000,0.000000,0.0000,0.00000
4,ENSG00000284332.1,MIR1302-2,0.00000,0.0000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.00000

In [10]:
#Check descriptions
hugo_ids = su2c_rna_harm['Description'].values.tolist()
su2c_rna_ensemble = su2c_rna_harm.drop(columns = ["Name"])
su2c_rna_ensemble.head()

,Description,SU2CLC-CLE-NIVO10-T1,SU2CLC-CLE-NIVO18-T1,SU2CLC-CLE-NIVO19-T1,SU2CLC-CLE-NIVO2-T1,SU2CLC-CLE-NIVO20-T1,SU2CLC-CLE-NIVO21-T1,SU2CLC-CLE-NIVO24-T1,SU2CLC-CLE-NIVO3-T1,SU2CLC-CLE-NIVO31-T1,...,SU2CLC-MSK-A2013-T1,SU2CLC-MSK-A2014-T1,SU2CLC-MSK-A2060-T1,SU2CLC-MSK-A2075-T1,SU2CLC-UCD-1124-T1,SU2CLC-UCD-1137-T1,SU2CLC-UCD-1142-T1,SU2CLC-UCD-1143-T1,SU2CLC-UCD-1557-T1,SU2CLC-UCD-1560-T1
0,DDX11L1,0.00000,0.0000,0.465325,0.663131,0.038447,0.0000,0.036191,0.083753,0.000000,...,0.057543,0.009227,0.00000,0.056734,0.018465,0.507545,0.02658,0.236091,0.0000,0.15309
1,WASH7P,1.72811,13.2271,17.226100,9.344120,10.023100,44.2401,0.511251,9.400640,0.974661,...,9.951610,1.315370,1.37496,7.067370,6.450200,5.491240,4.19865,3.714150,55.4283,4.32528
2,MIR6859-1,0.00000,0.0000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.00000
3,MIR1302-2HG,0.00000,0.0000,0.000000,0.000000,0.000000,0.0000,0.215248,0.000000,0.429895,...,0.000000,0.000000,0.00000,0.000000,0.188272,0.047259,0.00000,0.000000,0.0000,0.00000
4,MIR1302-2,0.00000,0.0000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.00000

In [22]:
expression_matrix = su2c_rna_ensemble.set_index('Description')
sum_expression = expression_matrix.sum(axis = 1)
zero_genes = sum_expression[sum_expression == 0].keys().tolist()

variances_expression = expression_matrix.var(axis = 1)
near_zero_var = variances_expression[variances_expression <= 0.01].keys().tolist()

remove_genes = set(zero_genes) | set(near_zero_var)

cleaned_expression_matrix = expression_matrix.drop(index = remove_genes)
# cleaned_expression_matrix.to_csv('cleaned_rna_expression.csv', index = True)

In [12]:
cleaned_expression_matrix

,SU2CLC-CLE-NIVO10-T1,SU2CLC-CLE-NIVO18-T1,SU2CLC-CLE-NIVO19-T1,SU2CLC-CLE-NIVO2-T1,SU2CLC-CLE-NIVO20-T1,SU2CLC-CLE-NIVO21-T1,SU2CLC-CLE-NIVO24-T1,SU2CLC-CLE-NIVO3-T1,SU2CLC-CLE-NIVO31-T1,SU2CLC-CLE-NIVO47-T1,...,SU2CLC-MSK-A2013-T1,SU2CLC-MSK-A2014-T1,SU2CLC-MSK-A2060-T1,SU2CLC-MSK-A2075-T1,SU2CLC-UCD-1124-T1,SU2CLC-UCD-1137-T1,SU2CLC-UCD-1142-T1,SU2CLC-UCD-1143-T1,SU2CLC-UCD-1557-T1,SU2CLC-UCD-1560-T1
Description,,,,,,,,,,,,,,,,,,,,,
DDX11L1,0.000000,0.00000,0.465325,0.663131,0.038447,0.000000,0.036191,0.083753,0.000000,0.000000,...,0.057543,0.009227,0.00000,0.056734,0.018465,0.507545,0.026580,0.236091,0.00000,0.15309
WASH7P,1.728110,13.22710,17.226100,9.344120,10.023100,44.240100,0.511251,9.400640,0.974661,0.188210,...,9.951610,1.315370,1.37496,7.067370,6.450200,5.491240,4.198650,3.714150,55.42830,4.32528
OR4F5,0.000000,0.00000,0.000000,1.879960,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.069799,0.000000,0.000000,0.000000,0.00000,0.00000
RP11-34P13.7,0.006596,0.00000,0.009421,0.000000,0.035805,0.908675,0.008426,0.007800,0.117800,0.000000,...,0.062521,0.000000,0.00000,0.000000,0.008598,0.009712,0.074262,0.048097,0.06421,0.00000
RP11-34P13.15,10.253400,16.02570,14.784600,2.285830,28.714300,98.931400,1.455420,5.543030,41.276100,98.266200,...,7.184690,1.060240,10.72470,44.262300,13.918300,11.823200,16.553200,12.987000,41.51130,8.61918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MT-ND5,21.062800,12.01930,22.180700,45.857600,109.262000,0.000000,21.519400,40.369800,35.365700,25.430300,...,70.194000,0.751003,4.71833,9.370700,0.601147,50.648100,17.637400,107.222000,11.75100,13.19260
MT-ND6,3.417180,10.99140,27.546500,62.153100,95.420700,0.131612,8.910330,51.924800,30.097500,27.499100,...,83.735700,0.609890,7.43937,14.624400,0.915360,61.807900,17.129100,142.391000,5.01275,10.37150
MT-TE,0.000000,0.00000,0.000000,1.852710,0.966747,0.000000,3.640050,0.421194,0.000000,0.818912,...,0.000000,0.000000,0.00000,1.426570,0.000000,0.000000,0.000000,0.742061,1.73366,0.00000
MT-CYB,2.369250,9.78848,29.625700,41.622600,74.598000,0.605577,7.594350,39.429100,11.925100,14.708100,...,44.741100,0.561248,3.79872,3.580170,0.224628,29.274400,12.772100,72.944000,3.98392,11.63940
MT-TP,0.000000,0.00000,0.000000,3.289920,0.000000,0.000000,0.461698,0.000000,0.000000,0.415477,...,0.489394,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000

In [118]:
log2tpm_matrix = np.log2(cleaned_expression_matrix + 1)

log2tpm_threshold = 0.5
min_sample_percent = 0.30

# Calculate percentage of samples where each gene passes threshold (axis=1 for row-wise)
percent_expressed = (log2tpm_matrix > log2tpm_threshold).sum(axis=1) / log2tpm_matrix.shape[1]

# Create filter:  keep genes expressed in >= 30% of samples
genes_to_keep = percent_expressed >= min_sample_percent

# Step 3: Apply filter to original TPM matrix
filtered_tpm_matrix = cleaned_expression_matrix[genes_to_keep]

# Print results
print(f"Original genes: {len(cleaned_expression_matrix)}")
print(f"Filtered genes: {len(filtered_tpm_matrix)}")
print(f"Genes removed: {len(cleaned_expression_matrix) - len(filtered_tpm_matrix)}")

# Save filtered TPM matrix
# filtered_tpm_matrix.to_csv('filtered_tpm_matrix.csv')

Original genes: 31450
Filtered genes: 21969
Genes removed: 9481

In [119]:
cleaned_expression_matrix_t = filtered_tpm_matrix.T
cleaned_expression_matrix_t.to_csv('cleaned_rna_expression.csv', index = True)

In [76]:
rna_id_expression = cleaned_expression_matrix_t.index.tolist()

## **Cleaning Clinical Data**

In [98]:
annot_file = 'Table_S1_Clinical_Annotations.xlsx'
su2c_clinical = pd.read_excel(source_data_path_clinical + annot_file,skiprows=2).set_index('Harmonized_SU2C_Participant_ID_v2')

In [101]:
su2c_clinical_extra = pd.read_csv\
    (source_data_path_clinical+'SU2C-MARK_Harmonized_Clinical_Annotations_Supplement_v1.txt',sep='\t')

In [102]:
su2c_clinical_extra = su2c_clinical_extra.set_index('Harmonized_SU2C_Participant_ID_v2')

In [103]:
df_merge = pd.concat([su2c_clinical, su2c_clinical_extra], axis = 1)

In [104]:
df_merge.loc['SU2CLC-DFC-DF0241',"Patient_Age_at_Diagnosis"] = 89
df_merge["Patient_Age_at_Diagnosis"] = (
    df_merge["Patient_Age_at_Diagnosis"]
    .astype("Int64")   # NOT "int"
)

In [122]:
df_merge["Patient_Smoking_Status"] = df_merge["Patient_Smoking_Status"].round(0)
df_merge["Patient_Smoking_Status"] = df_merge["Patient_Smoking_Status"].astype("Int64")

In [123]:
#Follow Table 1 in publication of Ravi et el.
keep_cols = ['Harmonized_SU2C_RNA_Tumor_Sample_ID_v2','Patient_Age_at_Diagnosis',"Patient_Sex","Patient_Smoking_Status","Patient_Smoking_Pack_Years_Harmonized",
            "Histology_Harmonized","PDL1_TPS","Line_of_Therapy","Agent_PD1_Category","Harmonized_PFS_Event",
            "Harmonized_OS_Event","Harmonized_PFS_Months","Harmonized_OS_Months","Harmonized_Confirmed_BOR_3_Cat","Advanced_Diagnosis_Date_Positive"]

clean_clinical_df = df_merge[keep_cols]
clean_clinical_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 393 entries, SU2CLC-CLE-NIVO1 to SU2CLC-YAL-2547
Data columns (total 15 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Harmonized_SU2C_RNA_Tumor_Sample_ID_v2  152 non-null    object
 1   Patient_Age_at_Diagnosis                389 non-null    Int64
 2   Patient_Sex                             389 non-null    object
 3   Patient_Smoking_Status                  389 non-null    Int64
 4   Patient_Smoking_Pack_Years_Harmonized   381 non-null    float64
 5   Histology_Harmonized                    389 non-null    object
 6   PDL1_TPS                                224 non-null    float64
 7   Line_of_Therapy                         389 non-null    float64
 8   Agent_PD1_Category                      389 non-null    object
 9   Harmonized_PFS_Event                    366 non-null    float64
 10  Harmonized_OS_Event                     383 non-null    float64
 11  Harmonized_PFS_Months                   366 non-null    float64
 12  Harmonized_OS_Months                    382 non-null    float64
 13  Harmonized_Confirmed_BOR_3_Cat          377 non-null    object
 14  Advanced_Diagnosis_Date_Positive        347 non-null    float64
dtypes: Int64(2), float64(8), object(5)
memory usage: 58.0+ KB

In [124]:
clean_clinical_df.to_csv('clean_clinical_data.csv', index = True)